name: Pipeline Continous Integration for a sîmple nodejs 

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: fabstock2/source-app:0.0.1-lamanu
    
    steps:

    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm ci
      working-directory: /source-app/

    - name: test du index.js 
      run: npm run test
      working-directory: /source-app/

    - name: run lint 
      run: npm run lint
      working-directory: /source-app/
